- Makefile
Test if we can push code from private mirror feature branch to airlock branch, now it's the public repo.
> Initial commit on airlock feature branch (#1)

- examples/configurations/dedicated-vnet-peering-azure-kafka-acls/README.md
- examples/configurations/dedicated-vnet-peering-azure-kafka-rbac/README.md
Add additional step in Azure peering TF example notes as in [official doc](https://docs.confluent.io/cloud/current/networking/peering/azure-peering.html)
> Update Azure peering TF notes

- docs/resources/confluent_catalog_entity_attributes.md
This PR updates the TF documentation for the `confluent_catalog_entity_attributes` resource by adding an example of how to set a schema, environment, or Kafka cluster description.
> API-2466: Update confluent_catalog_entity_attributes.md 

- examples/configurations/private-link-schema-registry/main.tf
https://confluentinc.atlassian.net/browse/APIT-2493
> [APIT-2493] Update e2e example for PLSR to use SR cluster data source instead of SR region data source and SR cluster resource 

- examples/configurations/flink_artifact/README.md
- examples/configurations/flink_artifact/main.tf
- examples/configurations/flink_artifact/variables.tf
https://confluentinc.atlassian.net/browse/CLI-3310
Result after terraform apply:
Terraform plan result to ensure no TF drift:
References
https://docs.confluent.io/cloud/current/flink/how-to-guides/create-udf.html
> [CLI-3310] End-to-end example of flink UDF 

- docs/resources/confluent_flink_artifact.md
- go.mod
- go.sum
- internal/provider/data_source_fink_artifact.go
- internal/provider/data_source_flink_artifact_test.go
- internal/provider/resource_flink_artifact.go
- internal/provider/resource_flink_artifact_test.go
https://confluentinc.atlassian.net/browse/APIT-2642
> APIT-2642 - Add Environment field as required for all flink UDF commands

- docs/data-sources/confluent_schema_registry_cluster_config.md
- docs/data-sources/confluent_subject_config.md
- docs/resources/confluent_schema_registry_cluster_config.md
- docs/resources/confluent_subject_config.md
- internal/provider/data_source_schema_registry_cluster_config.go
- internal/provider/data_source_schema_registry_cluster_config_provider_block_test.go
- internal/provider/data_source_schema_registry_cluster_config_test.go
- internal/provider/data_source_subject_config.go
- internal/provider/data_source_subject_config_provider_block_test.go
- internal/provider/data_source_subject_config_test.go
- internal/provider/resource_schema_registry_cluster_config.go
- internal/provider/resource_schema_registry_cluster_config_provider_block_test.go
- internal/provider/resource_schema_registry_cluster_config_test.go
- internal/provider/resource_subject_config.go
- internal/provider/resource_subject_config_provider_block_test.go
- internal/provider/resource_subject_config_test.go
- internal/testdata/schema_registry_cluster_compatibility_level/read_created_schema_registry_cluster_compatibility_level.json
- internal/testdata/schema_registry_cluster_compatibility_level/read_updated_schema_registry_cluster_compatibility_level.json
- internal/testdata/subject_compatibility_level/read_created_subject_compatibility_level.json
- internal/testdata/subject_compatibility_level/read_updated_subject_compatibility_level.json
https://confluentinc.atlassian.net/browse/FF-18395
https://confluent.slack.com/archives/CGX4EL0Q3/p1731700446189009
Testing strategy doc: https://docs.google.com/document/d/10SnOfUS-3aYgEt4-6VxcvzrZiXJdbmrnZ_3z2ZtAJsY/edit?usp=sharing
> [APIT-2486] - Terraform support for compatibilityGroup property for a Schema subject config

- docs/resources/confluent_peering.md
> APIT-2697: Fix Documentation Typo in confluent_peering.md

- internal/provider/resource_flink_artifact.go
Release Notes
---------
New Features
Bug Fixes
- Added `environmentId` to predesigned URL step for `flink artifact create`.
Examples
Checklist
---------
What
----
Add environment to predesigned URL step
References
----------
https://confluentinc.atlassian.net/browse/FF-19935
Test & Review
-------------
DOne manual testing to mitigate the customer issue
> FF-19935 - Add environment to predesigned URL step

- .github/pull_request_template.md
Release Notes
---------
New Features
- Improve the PR template file description and checklist items.
Checklist
---------
What
----
The update on the `pull_request_template.md` file, changes include:
- Add the `Blast Radius` section.
- PR owner should specify which test environment the feature is enabled in the checklist.
- Update `TF acceptance tests` -> `TF acceptance or unit tests`.
- Some grammar level update.
References
----------
https://confluentinc.atlassian.net/wiki/spaces/AEGI/pages/3938058831/Confluent+Terraform+provider+developer+contributing+and+PR+approval+requirements
https://confluentinc.atlassian.net/browse/APIT-2737
Test & Review
-------------
Since this PR only impacts a MD file, no test is required.
> [APIT-2737] Improve the PR request template file and add Blast Radius section

- internal/provider/resource_schema.go
- internal/provider/resource_schema_latest_refresh_test.go
- internal/provider/resource_schema_latest_test.go
- internal/provider/resource_schema_versioned_provider_block_test.go
- internal/provider/resource_schema_versioned_test.go
- internal/testdata/schema_registry_schema/read_latest_schema.json
- internal/testdata/schema_registry_schema/read_latest_schema_updated.json
Release Notes
---------
New Features
Bug Fixes
- Support  ruleSet removal via `confluent_schema` resource
Examples
Checklist
---------
What
----
Support  ruleSet removal via `confluent_schema` resource
Blast Radius
----
All customers using confluent schema rulesets.
References
----------
https://confluentinc.atlassian.net/browse/RCCA-23805
Test & Review
-------------
Updated integration tests. 
Manual testing Doc: https://docs.google.com/document/d/1XgZRsEd6VU2PySVcjCuOxnV2WAyAK_MufnBjiiN6ibc/edit?tab=t.0
> Cannot remove `ruleSet` via terraform resource `confluent_schema`

- docs/data-sources/confluent_schema_registry_cluster.md
- docs/data-sources/confluent_schema_registry_clusters.md
Release Notes
---------
Bug Fixes
- Updated docs for [confluent_schema_registry_clusters](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_schema_registry_clusters) data source.
Checklist
---------
NA
What
----
This PR updates the doc to fix tiny typos.
Blast Radius
----
NA
References
----------
NA
Test & Review
-------------
NA
> Update docs for confluent_schema_registry_clusters data source

- CHANGELOG.md
Release Notes
---------
NA
Checklist
---------
What
----
This PR adds a tiny note to our CHANGELOG.md file:
Blast Radius
----
NA
References
----------
NA
Test & Review
-------------
NA
> Add a note to CHANGELOG.md.

- examples/configurations/flink-quickstart/main.tf
Release Notes
---------
Examples
- Updated fllink-quickstart example.
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------
> Update flink-quickstart example to have 2 additional role bindings

- internal/testdata/apikey/read_list_tableflow_regions_200.json
- internal/testdata/apikey/read_list_tableflow_regions_401.json
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Followup to the previous PR. These json files for the acceptance tests weren't included.
Blast Radius
----
References
----------
Test & Review
-------------
> Add missing tableflow apikey test files

- docs/resources/confluent_tableflow_topic.md
- examples/configurations/tableflow/byob-aws-storage/README.md
- examples/configurations/tableflow/byob-aws-storage/iam_role_module/main.tf
- examples/configurations/tableflow/byob-aws-storage/iam_role_module/variables.tf
- examples/configurations/tableflow/byob-aws-storage/main.tf
- examples/configurations/tableflow/byob-aws-storage/outputs.tf
- examples/configurations/tableflow/byob-aws-storage/schemas/avro/purchase.avsc
- examples/configurations/tableflow/byob-aws-storage/variables.tf
Release Notes
---------
Examples
- Added new [`byob-aws-storage`](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/tableflow/byob-aws-storage) example for Tableflow.
Checklist
---------
NA
What
----
This PR adds a new [`byob-aws-storage`](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/tableflow/byob-aws-storage) example for Tableflow.
Blast Radius
----
NA
References
----------
NA
Test & Review
-------------
* https://confluent.slack.com/archives/C08H9NWM0TG/p1742343969368569
> Add byob-aws-storage example for Tableflow

- docs/resources/confluent_tableflow_topic.md
- examples/configurations/tableflow/byob-aws-storage/README.md
- examples/configurations/tableflow/confluent-managed-storage/README.md
Release Notes
---------
Bug Fixes
- Updated docs.
Checklist
---------
NA
What
----
This PR updates Tableflow docs & examples' README files.
Blast Radius
----
NA
References
----------
NA
Test & Review
-------------
NA
> Update Tableflow docs and examples

- docs/data-sources/confluent_business_metadata_binding.md
- docs/data-sources/confluent_tag_binding.md
- docs/resources/confluent_business_metadata_binding.md
- docs/resources/confluent_tag_binding.md
Release Notes
---------
Bug Fixes
- Updated docs.
Checklist
---------
NA
What
----
This PR updates the attribute description of entity_name.
Blast Radius
----
NA
References
----------
NA
Test & Review
-------------
NA
> Update the attribute description of entity_name.

- examples/configurations/private-link-schema-registry/main.tf
- internal/provider/data_source_schema_registry_clusters_test.go
- internal/provider/resource_kafka_cluster.go
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Update endpoint name to plural.
Blast Radius
----
None
References
----------
Test & Review
-------------
https://docs.google.com/document/d/1CXTqoo3Lka8RXKtk9cDVCqNN853enSEhlzMUMrXsFkg/edit?tab=t.0
> Update regional endpoint name to plural

- examples/configurations/private-link-schema-registry/main.tf
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Update endpoint of PLSR example to remove deprecated endpoint and use new one
Blast Radius
----
None
References
----------
Test & Review
-------------
n/a
> PLSR example endpoint update

- docs/index.md
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
This PR only includes a documentation change for the Terraform OAuth support, no real source code change, skip most of the description sections.
Blast Radius
----
References
----------
Test & Review
-------------
> Add the EA label and messages to the OAuth block doc

- docs/resources/confluent_certificate_authority.md
- go.mod
- go.sum
- internal/provider/resource_certificate_authority.go
Release Notes
---------
New Features
Bug Fixes
- This PR updates the Terraform docs and associated CCloud SDK version for certificate authority resource.
Examples
Checklist
---------
What
----
This PR updates the Terraform docs and associated CCloud SDK for certificate authority resource.
Blast Radius
----
No real impact, just the documentation update to reflect the correct description.
References
----------
https://docs.confluent.io/cloud/current/api.html#tag/Certificate-Authorities-(iamv2)/operation/createIamV2CertificateAuthority
https://confluent.slack.com/archives/C06M2N4SV7F/p1744142027102489?thread_ts=1734476682.059809&cid=C06M2N4SV7F
Test & Review …
> Update the docs and sdk for certificate authority

- docs/guides/version-2-upgrade.md
Release Notes
---------
Bug Fixes
- Updated the docs.
Checklist
---------
NA
What
---- 
This PR updates ["Confluent Provider 2.0.0: Upgrade Guide"](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/sample-project).
Blast Radius
----
NA
References
----------
* https://confluent.slack.com/archives/C01880K2BAA/p1744661791318769?thread_ts=1744660174.851019&cid=C01880K2BAA
Test & Review
-------------
Doc Preview Tool: https://registry.terraform.io/tools/doc-preview
> Add a note to the "Confluent Provider 2.0.0: Upgrade Guide".

- docs/guides/version-2-upgrade.md
Release Notes
---------
Bug Fixes
- Updated the docs.
Checklist
---------
NA
What
----
This PR updates the "Confluent Provider 2.0.0: Upgrade Guide" doc.
Blast Radius
----
NA
References
----------
NA
Test & Review
-------------
* https://confluent.slack.com/archives/C08H9NWM0TG/p1744700800264649
* https://confluent.slack.com/archives/C01880K2BAA/p1744831445153669
Doc Preview Tool: https://registry.terraform.io/tools/doc-preview
> INC-1494: Update the "Confluent Provider 2.0.0: Upgrade Guide" doc

- docs/index.md
- internal/provider/resource_catalog_integration.go
- internal/provider/resource_tableflow_topic.go
- internal/provider/utils.go
Release Notes
---------
New Features
- Remove the OAuth support for Tableflow APIs.
Bug Fixes
Examples
Checklist
---------
What
----
Currently, OAuth support is not enabled for Tableflow APIs which is mis-documented earlier, so this PR removes the OAuth support and users should still use the Tableflow specific API key/secret for the authentication.
Blast Radius
----
None, since the earlier OAuth changes are not released yet.
References
----------
https://confluent.slack.com/archives/C07H7TJCR45/p1744748790337429
Test & Review
-------------
Not applicable since this is not an additive change.
> Tableflow APIs don't support OAuth at this moment

- .semaphore/semaphore.yml
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------
> Upgrade Semaphore agent to the next tier

- docs/resources/confluent_schema.md
Release Notes
---------
Bug Fixes
- Updated the docs.
Checklist
---------
NA
What
----
This PR adds a new note to confluent_schema.md docs, explaining how to create a subject in a specific context.
Blast Radius
----
None.
References
----------
* https://support.confluent.io/hc/en-us/articles/33847910217492-What-are-the-Best-Practices-for-naming-Schema-Contexts
* https://docs.confluent.io/cloud/current/sr/schema-linking.html#qualified-subjects
* https://docs.confluent.io/platform/current/schema-registry/develop/api.html#get--contexts
Test & Review
-------------
We applied the following TF config:
```
resource "confluent_schema" "key" {
subject_name = "key"
format       = "AVRO"
schema       = file("./schemas/avro/key.avsc")
}
resource "confluent_schema" "purchase2" {
subject_name = …
```
> Update confluent_schema.md docs

- service.yml
Checklist
---------
What
----
This disables the `make` plugin and fixes the syntax of the `sonarqube` plugin in `service.yml`. Recently, https://github.com/confluentinc/terraform-provider-confluent/pull/641 was merged, which likely caused some issues, but that isn't specified, and then reverted in https://github.com/confluentinc/terraform-provider-confluent/pull/663. With the new contents of `service.yml`, I expect that service bot will generate subsequent updates as desired.
Blast Radius
----
This change impacts only the pipeline used for testing and validation. It will not impact any existing functionality. In the worst case scenario, validation for new builds will fail.
References
----------
N/A
Test & Review
-------------
Existing tests pass.
> fix service.yml

- CHANGELOG.md
- service.yml
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------
> #minor: prepare for v2.30.0 minor release

- Makefile
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------
> #minor: prepare for v2.30.0 minor release: temporarily switch default bump to minor

- Makefile
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------
> Revert default bump to patch

- docs/resources/confluent_schema.md
Release Notes
---------
Bug Fixes
- Updated the docs of confluent_schema [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema) to document a workaround for issue ([#619](https://github.com/confluentinc/terraform-provider-confluent/issues/619)).
Checklist
---------
What
----
This PR updates the docs of confluent_schema [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema) to document a workaround for issue ([#619](https://github.com/confluentinc/terraform-provider-confluent/issues/619))..
Blast Radius
----
NA
References
----------
* https://confluentinc.atlassian.net/browse/APIE-408
* https://confluent.slack.com/archives/C075H73ATEX/p1748066358494289?thread_ts=1748044578.2 …
> APIE-408: Update Terraform documentation for confluent_schema to document a workaround for issue #619.

- Makefile
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------
> Revert default bump to patch 

- Makefile
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------
> #minor: prepare for v2.32.0 minor release: temporarily switch default bump to minor

- .semaphore/goreleaser.yml
This PR should fix CI failure.
* https://confluent.slack.com/archives/C09EP1SS3/p1751472042412479?thread_ts=1751411143.543079&cid=C09EP1SS3
> #minor: prepare for v2.33.0 minor release: Fix "Permission denied (os error 13)".

- Makefile
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------
> Revert default bump to patch away from minor version

- Makefile
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------
> #minor Prepare for 2.34.0 release.

- Makefile
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------
> Set bump to patch

- Makefile
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------
> Change default bump type back to `patch` after release

- docs/LIVE_TESTING_TEMPLATE.md
- internal/provider/resource_api_key_live_test.go
- internal/provider/resource_invitation_live_test.go
- internal/provider/resource_kafka_acl_live_test.go
- internal/provider/resource_role_binding_live_test.go
- internal/provider/resource_schema_live_test.go
- internal/provider/resource_schema_registry_cluster_config_live_test.go
- internal/provider/resource_schema_registry_cluster_mode_live_test.go
- internal/provider/resource_service_account_live_test.go
- internal/provider/resource_subject_config_live_test.go
- internal/provider/resource_subject_mode_live_test.go
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Add comprehensive live test coverage for 10 core resources including service accounts, API keys, role bindings, and complete Schema Registry suite with advanced testing patterns and documentation.
Blast Radius
----
No blast radius, test additions only.
References
----------
Test & Review
-------------
Passing pipeline for live tests: https://semaphore.ci.confluent.io/jobs/f7bf5b0b-f619-40ba-966d-1ab940b8008c
> Expanded live test coverage to API keys, role bindings, schema registry, and service accounts

- internal/provider/resource_kafka_cluster_live_test.go
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
We will disable the live tests that verify provisioning/deprovisioning of dedicated clusters while we figure out the right strategy on how often we run these as they are cost intensive and deprovisioning takes up to 18 hours: [slack thread](https://confluent.slack.com/archives/C08SCSN4TNV/p1753462773897359?thread_ts=1753400447.529869&cid=C08SCSN4TNV)
Blast Radius
----
Testing change only
References
----------
Test & Review
-------------
> Disable live testing for dedicated Kafka clusters

- internal/provider/resource_schema.go
Release Notes
---------
New Features
Bug Fixes
- Enable update for `confluent_schema` when only the metadata field changes.
Examples
Checklist
---------
What
----
Resolves TF: issue #740 where changes are not getting reflected when only metadata is being updated.
Blast Radius
----
`confluent_schema` update functionality could be impacted
References
----------
https://confluentinc.atlassian.net/browse/APIE-485
Test & Review
-------------
Manual testing Link: https://docs.google.com/document/d/1vX3JeSxtW8nxOzyGMjg8wrc1SbsvjludoZfSAXIwBU8/edit?tab=t.0
> [APIE-485] - Confluent_schema metdata changes not reflecting

- Makefile
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------
> Revert DEFAULT_BUMP to patch

- .semaphore/goreleaser.yml
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------
> #minor Prepare for 2.39.0 - test GPG_TTY

- .goreleaser.yml
- .semaphore/goreleaser.yml
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Blast Radius
----
References
----------
Test & Review
-------------
> #minor Prepare for 2.39.0 - pinentry

- internal/provider/data_source_identity_pool_live_test.go
- internal/provider/data_source_identity_provider_live_test.go
- internal/provider/resource_identity_pool_live_test.go
- internal/provider/resource_identity_provider_live_test.go
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
This PR creates comprehensive live testing for the Identity Provider & Identity Pool resources and data sources.
Blast Radius
----
None, this is for internal testing.
References
----------
Test & Review
-------------
The tests pass locally and also pass in the Semaphore Pipeline: https://semaphore.ci.confluent.io/jobs/6f88e340-6085-486d-a191-cebd4cda8aff
> Comprehensive Live Testing for Identity Provider & Identity Pool resources and data sources

- internal/provider/oauth.go
- internal/provider/resource_schema_exporter.go
This PR reverts #847 to exclude it from the upcoming hot-fix release.
> Revert PR #847.
