confluentinc/terraform-provider-confluent

docs/guides/version-2-upgrade.md
This PR addresses the documentation issue https://github.com/confluentinc/terraform-provider-confluent/issues/412.
- Fix typos in `version-2-upgrade.md`.
=> Fix typos in docs/guides/version-2-upgrade.md

internal/provider/resource_flink_statement.go, internal/provider/utils_wait.go
This PR updates the timeout for `confluent_flink_statement` provisioning to 6 hours to resolve timeout issues.
=> API-2397: Update timeout for confluent_statement

internal/provider/resource_api_key.go, internal/provider/utils_test.go
This PR resolves https://github.com/confluentinc/terraform-provider-confluent/issues/418.
In short, the issue is `isSchemaRegistryApiKey()` was only expecting for `srcm/v3` API version instead of any of `srcm/v2` or `srcm/v3`.
The API Keys Mgmt API doesn't require `api_version` in the request and it does return `resource.api_version=srcm/v2` by default:
```
➜  ✗ curl --request POST \
--url https://api.confluent.cloud/iam/v2/api-keys \
--header 'Authorization: Basic ...' \
--header 'content-type: application/json' \
--data '{"spec":{"display_name":"test2","owner":{"id":"sa-6zzw98"},"resource":{"id":"lsrc-kkg0rg","kind":"SchemaRegistry"}}}'
{
"api_version": "iam/v2",
"id": "OZSKBWUZFIF6QHUM",
"kind": "ApiKey",
"metadata": {
"created_at": "2024-08-23T14:15:30.4238Z",
"resource_name": …
```
=> APIT-2468: Resolve "Error: unexpected API Key "... resource" when creating SR confluent_api_key 

docs/resources/confluent_flink_statement.md, go.mod, go.sum, internal/provider/resource_flink_statement.go, internal/provider/resource_flink_statement_provider_block_test.go, internal/provider/resource_flink_statement_test.go, internal/provider/utils_wait.go, internal/testdata/flink_statement/read_resumed_flink_statement.json
Support for Flink statement resume feature:
1. Differentiate the `flinkStatementUpdate` function into `flinkStatementResume` and `flinkStatementStop`.
2. Allow the Flink statement to be resumed from `stopped` = true -> false scenario.
3. Update all ACC test cases with additional scenario to resume the Flink statement.
The successfully test step-by-step TF procedure with real infrastructure can be found here (Confluent Only):
https://docs.google.com/document/d/163ffPHucuITuUWV3ptDKMDTJzrWKs9BHdKHcIeNNan0/edit#heading=h.a96w50hs5wqs
=> [APIT-884] Support for Flink statement resume feature (#40)

internal/provider/resource_schema_exporter.go, internal/provider/utils_wait.go
This PR is a follow up to #462 where I forgot to update internal provisioning function of SR exporter. It
* Starts using schemaExporterAPICreateTimeout in the internal provisioning function, which is the component that actually triggers the error (timeout after 10 minutes).
* Reduces the schemaExporterAPICreateTimeout from 24 hours to 4 hours, as 4 hours should be sufficient even for huge users with 20k+ schemas (assuming it takes 40 minutes to export 4k schemas).
=> Fix SR exporter provisioning issues

docs/resources/confluent_role_binding.md
This PR updates confluent_role_binding.md to include an example for a `confluent_schema_registry_kek` resource.
=> Update confluent_role_binding.md to include an example for a Kek resource

.semaphore/goreleaser.yml
This PR should solve the error in `goreleaser-darwin-fips` job.
The root cause is our previous CI builds used gpatch--2.7.6.arm64_ventura.bottle.tar.gz, while the most recent (failed) one used gpatch--2.7.6.arm64_ventura.bottle.1.tar.gz. This indicates that there’s a slight difference in the bottles (likely a minor patch or metadata update).
Based on the output, the key differences between the two installations of `gpatch` seem to be:
**Different Bottle Versions**:
- The first installation used `gpatch--2.7.6.arm64_ventura.bottle.tar.gz`, while the second used `gpatch--2.7.6.arm64_ventura.bottle.1.tar.gz`. This indicates that there’s a slight difference in the bottles (likely a minor patch or metadata update).
In the second installation, there’s an additional message in the …
=> Fix "syntax error: package statement must be first"

docs/data-sources/confluent_certificate_authority.md, docs/data-sources/confluent_certificate_pool.md, docs/resources/confluent_certificate_authority.md, docs/resources/confluent_certificate_pool.md
This PR updates the TF docs to match corresponding APIs:
* https://docs.confluent.io/cloud/current/api.html#tag/Certificate-Authorities-(iamv2)
* https://docs.confluent.io/cloud/current/api.html#tag/Certificate-Identity-Pools-(iamv2)
=> APIT-2632: Release confluent_certificate_authority, confluent_certificate pool as GA

docs/resources/confluent_flink_statement.md
Fix link in `confluent_flink_statement.md` to the [flink-carry-over-offset-between-statements](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/flink-carry-over-offset-between-statements) example.
=> minor: fix link in Flink statement docs

examples/configurations/flink-quickstart/statements/populate-orders-source-table.sql
Using our current statement example to insert data into Flink SQL database table will result in:
```
Query schema: [order_id: STRING NOT NULL, customer_id: INT NOT NULL, product_id: STRING NOT NULL, price: DOUBLE NOT NULL]
│ Sink schema:  [key: BYTES, order_id: STRING, customer_id: INT, product_id: STRING, price: DOUBLE]
```
Reason being that the Sink schema has additional intrinsic key: BYTES, select everything from the sink schema will cause table mismatch and Flink statement creation failure.
Update the SQL statement explicitly select fields for insert operation between query and sink schema. 
https://confluentinc.atlassian.net/browse/APIT-2658
=> [APIT-2658] Update the SQL statement in example

docs/resources/confluent_flink_statement.md, internal/provider/resource_flink_statement.go, internal/provider/resource_flink_statement_provider_block_test.go, internal/provider/resource_flink_statement_test.go, internal/provider/utils_wait.go, internal/testdata/flink_statement/read_resumed_flink_statement.json, internal/testdata/flink_statement/read_resuming_flink_statement.json
This PR supports the feature of resume the Flink statement with a different principal/compute_pool.
Namely when `stopped` parameter has change from true -> false, we can update the `principal` and/or `compute_pool` in place and avoid recreating the Flink statement resource.
- Split the `flinkStatementUpdate()` into `flinkStatementStop()` and `flinkStatementResume()` due to different behaviors in the process of stop and resume.
- Add custom diff function `resourceFlinkStatementDiff()` to remind and avoid users running into invalid scenarios when initiating stop or resume.
- Update the Flink statement to remove `RESUMING` statement status.
- Add associated Terraform acceptance tests.
- Update the resource docs as instruction.
This PR also updates the Flink statement status type according to …
=> [CLI-3313] Resume Flink statement along with principal and/or compute_pool ID update

.github/pull_request_template.md
**Summary**
As of now, the PR template file for PR submission is missing, in order to improve the PR review and Terraform provider release process, add this `pull_request_template.md` file to help developers understand what to expect from the PR review process, and what kind of verification should be done before the PR is considered **ready**.
After this PR is merged, we should expect all following PRs to have the PR description area following this template.
**Reference**
https://confluentinc.atlassian.net/browse/APIT-2737
=> [APIT-2737] Add the GitHub PR template file to document the contributing requirement and checklist

.semaphore/goreleaser.yml
This PR fixes CI build error:
```
⨯ release failed after 0s                  error=missing GITHUB_TOKEN, GITLAB_TOKEN and GITEA_TOKEN
```
=> #minor: Fix CI build

docs/resources/confluent_flink_artifact.md, examples/configurations/flink_artifact/main.tf, internal/provider/data_source_fink_artifact.go, internal/provider/data_source_flink_artifact_test.go, internal/provider/resource_flink_artifact.go, internal/provider/resource_flink_artifact_test.go, internal/provider/utils.go, internal/testdata/flink_artifact/create_artifact.json, internal/testdata/flink_artifact/read_artifact.json, internal/testdata/flink_artifact/read_created_artifact.json
Checklist
---------
What
----
Align Flink Artifact Terraform with CLI deprecating Class field and adding `documentation_link`
Blast Radius
----
Confluent Cloud customers who are using `artifacts` resource as part of their Flink statements with UDFs will be blocked
References
----------
https://confluentinc.atlassian.net/browse/FRT-782
https://github.com/confluentinc/api/pull/1844
Test & Review
We run terraform plan and apply with the previously existing class parameter, and ensure there is no terraform drift:
We remove the class parameter, and add the documentation link parameter. Run terraform plan and apply and ensure no TF drift
-------------
We also want to do the version test. So we create a resource with terraform version 2.13.0, and run terraform apply and ensure there is no drift. …
=> [FRT-879] Align Flink Artifact Terraform with CLI

internal/provider/resource_api_key.go
Release Notes
---------
* Fixed the "Regression in v2.13.0: Unable to create API key with managed_resource block" issue (https://github.com/confluentinc/terraform-provider-confluent/issues/537).
Bug Fixes
* Fixed the "Regression in v2.13.0: Unable to create API key with managed_resource block" issue (https://github.com/confluentinc/terraform-provider-confluent/issues/537).
Examples
- NA
Checklist
---------
What
----
This PR disables `customdiff.Sequence(resourceApiKeyManagedResourceDiff)` for `confluent_api_key` as it doesn't support all use cases and leads to false positives in some scenarios. See issue #537 for more details regarding one of the use cases where it fails.
Blast Radius
----
- Confluent Cloud customers who are using `confluent_api_key` resource will be blocked.
References …
=> RCCA-25218: Fix "Unable to create API key with managed_resource block" issue

Makefile, go.mod, go.sum, internal/provider/resource_connector.go, internal/provider/resource_connector_managed_test.go
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Change `build` in the Makefile to not hardcode OS or architecture. And update the connect SDK to version 0.7.0.
Blast Radius
----
Should be minimal to none since this is only a renaming change, but any issues would affect the connector resource.
References
----------
Test & Review
-------------
Tested creating connector (datagen source) as a sanity check.
Create plan:
```
terraform plan
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration: …
```
=> Update Makefile and Connect SDK

internal/provider/resource_schema.go, internal/provider/resource_schema_latest_refresh_test.go, internal/provider/resource_schema_latest_test.go, internal/provider/resource_schema_versioned_provider_block_test.go, internal/provider/resource_schema_versioned_test.go, internal/testdata/schema_registry_schema/read_latest_schema.json, internal/testdata/schema_registry_schema/read_latest_schema_updated.json
Release Notes
---------
Bug Fixes
* Fixed "[error creating Schema: 403 Forbidden: Upgrade to Stream Governance Advanced package to use schema rules](https://github.com/confluentinc/terraform-provider-confluent/issues/543) ([#543](https://github.com/confluentinc/terraform-provider-confluent/issues/543)).
Checklist
---------
- [] I have included appropriate Terraform acceptance or unit tests for any new resource, data source, or functionality.
What
----
This PR fixes #543 by reverting #550. This works as we figured even `terraform plan` after `terraform init -upgrade` (2.14.0 -> 2.15.0) triggers
```
2025-01-31T10:05:13.570-0800 [DEBUG] plugin.terraform-provider-confluent_2.15.0: Creating new Schema: {"references":[],"ruleSet":{"domainRules":[]},"schema":"{\n  \"type\": \"record\",\n …
```
=> RCCA-25291: Fix issue #543

examples/configurations/connectors/s3-sink-connector-assume-role/main.tf, examples/configurations/field-level-encryption-schema/main.tf, examples/configurations/private-flink-quickstart/main.tf, examples/configurations/private-link-schema-registry/main.tf
- Updated 4 examples to use the latest version of TF Provider: 2.16.0 by using https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/version-2-upgrade. We also ran `terraform fmt` and `terraform validate` to resolve some minor errors:
```
terraform init 
Initializing modules...
- privatelink in 
Error: Unreadable module directory
Unable to evaluate directory symlink: lstat aws-privatelink-endpoint: no such
file or directory
```
and
```
Error: Unsupported argument
on main.tf line 238, in resource "confluent_schema" "order":
238:   private_rest_endpoint = data.confluent_schema_registry_cluster.essentials.private_rest_endpoint
An argument named "private_rest_endpoint" is not expected here.
```
Checklist
---------
What
----
- Updated 4 examples to use the latest …
=> Updated 4 examples to use the latest version of TF Provider: 2.16.0

.semaphore/goreleaser.yml
Release Notes
---------
NA
Checklist
---------
NA
Why did CI start to fail?
----
There was a recent change in GoReleaser's curl script: https://github.com/goreleaser/goreleaser/commit/fa7391e1818de028cd0947ac2ff1e613d9743183
What
----
This PR makes 2 changes to our Semaphore configs:
* adds `--force` flag to resolve
```
artifact push workflow dist/darwin-fips_darwin_amd64_v1
[Feb 11 18:03:34.613] Error pushing artifact: 'artifacts/workflows/314d3afb-0bcf-465e-8070-98592bf4b1f7/darwin-fips_darwin_amd64_v1/terraform-provider-confluent_2.17.0' already exists in the remote storage; delete it first, or use --force flag
```
when rerunning the CI `goreleaser-darwin-fips` task.
* explicitly set `DISTRIBUTION=pro` to resolve the issue with the following command
```
curl …
```
=> #minor: fix CI error for v2.17.0 minor release

.semaphore/goreleaser.yml
Release Notes
---------
NA
Checklist
---------
NA
What
----
This is a follow up to #533. Apparently, even though CI error suggested us to use `--force` flag:
```
artifact push workflow dist/darwin-fips_darwin_amd64_v1
[Feb 11 18:03:34.613] Error pushing artifact: 'artifacts/workflows/314d3afb-0bcf-465e-8070-98592bf4b1f7/darwin-fips_darwin_amd64_v1/terraform-provider-confluent_2.17.0' already exists in the remote storage; delete it first, or use --force flag
```
it isn't supported by `artifact` command:
```
artifact push --force workflow dist/darwin-fips_darwin_amd64_v1
Error: unknown flag: --force
Usage:
artifact push [command]
Available Commands:
job         Uploads a job file or directory to the storage.
project     Upload a project file or directory to the storage.
workflow    Uploads …
```
=> #minor: fix CI error for v2.17.0 minor release 

examples/configurations/regular-bidirectional-cluster-link-rbac/main.tf
Release Notes
---------
Examples:
- Update the `regular-bidirectional-cluster-link-rbac` example to avoid a potential race condition.
Checklist
---------
What
----
This PR updates the `regular-bidirectional-cluster-link-rbac` example to avoid a potential race condition. Adding a depends_on block should be sufficient, as there is already a 10-second [timeout](https://github.com/confluentinc/terraform-provider-confluent/blob/master/internal/provider/resource_cluster_link.go#L180) for cluster link resource creation.
We added 
```
depends_on = [
confluent_cluster_link.east-to-west
]
```
instead of
```
depends_on = [
confluent_cluster_link.west-to-east
]
```
to mirror our other TF example (`advanced-bidirectional-cluster-link-rbac`) and the …
=> APIT-2866: Update the regular-bidirectional-cluster-link-rbac example to avoid a potential race condition.

docs/data-sources/confluent_schema_registry_cluster.md
Release Notes
---------
Bug Fixes
- Updated docs for [confluent_schema_registry_cluster](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_schema_registry_cluster) data source.
Checklist
---------
NA
What
----
This PR updates the doc to fix a tiny typo as `id` is no longer a required input argument:
```
data "confluent_schema_registry_cluster" "example_using_env_id" {
environment {
id = "env-xyz456"
}
}
```
Blast Radius
----
NA
References
----------
NA
Test & Review
-------------
NA
=> Update docs for confluent_schema_registry_cluster data source

docs/data-sources/confluent_kafka_cluster.md, docs/resources/confluent_kafka_cluster.md
Release Notes
---------
Bug Fixes
- Updated docs for [confluent_kafka_cluster](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_kafka_cluster) resource / data source.
Checklist
---------
NA
What
----
This PR updates the doc to fix a tiny typo to remove Freight EA note as this feature has been released as GA [already](https://docs.confluent.io/cloud/current/release-notes/index.html#february-3-2025).
Blast Radius
----
NA
References
----------
NA
Test & Review
-------------
NA
=> CLI-3340: Remove typos from confluent_kafka_cluster docs

internal/provider/resource_connector.go
Release Notes
---------
Bug Fixes
- Updated `confluent_connector` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_connector) to resolve TF drift for custom connectors.
Checklist
---------
What
----
This PR resolves TF drift for custom connectors. For example, when running [custom-datagen-source-connector](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/connectors/custom-datagen-source-connector) example, users could have observed TF drift:
```
$ terraform plan
...
~ resource "confluent_connector" "source" {
~ config_nonsensitive = {
- "confluent.custom.plugin.type"       = "SOURCE" -> null
- "confluent.custom.plugin.version.id" = "ver-57p0dg" -> null
- …
```
=> APIT-2880: Resolve TF drift for custom connectors

docs/data-sources/confluent_access_point.md, docs/resources/confluent_access_point.md, examples/configurations/network-access-point-gcp-private-service-connect/main.tf, internal/provider/data_source_access_point.go, internal/provider/resource_access_point.go
Release Notes
---------
Bug Fixes
- Temporary fix for TF drift caused by access point resource recreation 
Checklist
---------
What
----
TLDR: Remove all occurrences of ALL_GOOGLE_APIS option in TF docs and examples as a temporary fix for TF drift caused by an access-point recreation incident. 
This root cause of the issue is that in GCP OPL command, both ALL_GOOGLE_APIS and all-google-apis are considered valid input for a PSC endpoint target, however, the current endpoint target response only return the value of all-google-apis regardless of the input. Consequently, a terraform drift occurs as it detects the endpoint target response is being different from the user input (i.e the user input the ALL_GOOGLE_APIS option). This PR updates the TF docs and examples to "hide" the …
=> Remove ALL_GOOGLE_APIS option from GCP OPL command

internal/provider/resource_kafka_topic.go, internal/provider/utils.go
Release Notes
---------
Bug Fixes
- Updated confluent_kafka_topic [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic) to add descriptive errors for any response formats.
Checklist
---------
- [] I have included appropriate Terraform acceptance or unit tests for any new resource, data source, or functionality.
What
----
Currently TF Provider for Confluent doesn't show a descriptive error messages in some scenarios (for example, if the error occurs before reaching the backend API). More specifically, if you have got the following configuration:
```
terraform {
required_providers {
confluent = {
source  = "confluentinc/confluent"
version = "2.17.0"
}
}
}
provider "confluent" {
kafka_api_key = "..."
kafka_api_secret = "..." …
```
=> APIT-2874: Show descriptive errors for any response formats for confluent_kafka_topic

internal/provider/resource_access_point.go, internal/provider/resource_access_point_test.go
Release Notes
---------
Bug Fixes
- A follow-up from a previous PR to ensure that no TF drift occurs for customers who already have resources created with the `ALL_GOOGLE_APIS` option 
Checklist
---------
What
----
This PR is a follow-up to a previous PR, and it updates the schema logics with a difference suppress function to ensure no Terraform drift occurs for customers who already have access point resources created with the now-disabled `ALL_GOOGLE_APIS` option. 
For more context, refer to the previous PR ([Remove ALL_GOOGLE_APIS option from GCP OPL command #562](https://github.com/confluentinc/terraform-provider-confluent/pull/562)). 
Blast Radius
----
- Customers using access point with GCP option with endpoint target specified as `ALL_GOOGLE_APIS` on Terraform.  
References …
=> Follow-up to ALL_GOOGLE_APIS option removal from GCP OPL command

internal/provider/resource_schema_latest_test.go, internal/provider/resource_schema_versioned_test.go
Release Notes
---------
NA
Checklist
---------
What
----
Update the `confluent_schema` resource tests to verify the request payload, ensuring that ruleset is not set to {} when ruleset is null in the Terraform configuration
Blast Radius
----
NA as this PR updates `*_test.go` files only.
References
----------
* https://confluentinc.atlassian.net/browse/APIT-2897
Test & Review
-------------
We also ran these tests using the 8c47c04d version, and verified that the tests would have failed, preventing a bug from being released:
```
➜  terraform-provider-confluent git:(8c47c04d) ✗ git log --pretty=oneline -n 2 | cat
8c47c04d3f68a3a5ffc3f900d8be2229593dda75 Cannot remove `ruleSet` via terraform resource `confluent_schema` (#500)
6a51ed0804915b36480c6fc41c5655e2d3b4e8b7 chore: patch version bump …
```
=> APIT-2897: Update the confluent_schema tests to verify the request payload

docs/resources/confluent_cluster_link.md, internal/provider/resource_cluster_link.go, internal/provider/resource_cluster_link_bidirectional_inbound_test.go, internal/provider/resource_cluster_link_bidirectional_outbound_test.go, internal/provider/resource_cluster_link_destination_inbound_test.go, internal/provider/resource_cluster_link_destination_outbound_test.go, internal/provider/resource_cluster_link_source_outbound_test.go
Release Notes
---------
New Features
- Add additional `cluster_link_id` attribute for `confluent_cluster_link` resource.
Bug Fixes
Examples
Checklist
---------
What
----
When customers send request to `catalog/v1/entity` endpoint, if the entity type is a Kafka cluster link, user is expected to pass in a qualified name with format of `<SR Cluster ID>/<Kafka Cluster ID>/<Kafka Cluster Link ID>`, such as `lsrc-5m375q:lkc-j825wq:_dg1_-GbTWSoo9D66WBeag`.
However in `confluent_cluster_link` resource, the Kafka cluster link ID is not visible, we should allow this additional attribute to be exposed to users in order to improve the user experience.
Blast Radius
---- …
=> [APIT-2896] Exposing additional attribution for cluster_link_id resource

internal/provider/resource_schema.go
Release Notes
---------
Bug Fixes
- Fixed "'~ schema = jsonencode # whitespace changes' TF drift for confluent_schema resource" issue (https://github.com/confluentinc/terraform-provider-confluent/issues/573).
Checklist
---------
What
----
**Context**: 
In short, https://github.com/confluentinc/terraform-provider-confluent/issues/573 only impacts users who used `2.15.0` version of TF Provider to manage `confluent_schema` resource.  We did [verify](https://confluent.slack.com/archives/C02TG07V058/p1741153197108959?thread_ts=1741153041.503299&cid=C02TG07V058) that we can't reproduce the issue when performing `2.10.0` -> `2.16.0` -> `2.18.0` updates, but we can reproduce it when doing `2.10.0` -> `2.15.0` -> `2.16.0`. Essentially, everyone who used `2.15.0` version of TF Provider to manage …
=> RCCA-25477: Fix "~ schema = jsonencode( # whitespace changes" TF drift for confluent_schema resource 

internal/provider/resource_group_mapping.go, internal/provider/resource_group_mapping_test.go, internal/testdata/group_mapping/read_updated_group_mapping.json
Release Notes
---------
Bug Fixes
- Updating the `filter` attribute of `confluent_group_mapping`-resource no longer triggers resource replacement, aligning the Terraform provider with Confluent UI behavior.
Checklist
---------
What
----
In previous versions of the Terraform provider, changing the `filter` attribute resulted in a replacement instead of an update.
Using the Confluent UI, it was always possible to update the filter without replacing the group mapping.
Previous versions:
```
-/+ resource "confluent_group_mapping" "group_mapping" {
~ filter       = "\"Old-Group-Name\" in groups" -> "\"New-Group-Name\" in groups" # forces replacement
~ id           = "group-EMBR" -> (known after apply)
}
```
With this pr:
```
~ resource "confluent_group_mapping" "group_mapping" {
~ filter …
```
=> Allow updates to `filter` attribute for Group Mapping without forcing resource re-creation

go.mod, go.sum, internal/provider/resource_service_account.go, internal/provider/resource_service_account_test.go, internal/testdata/service_account/read_updated_sa.json
Release Notes
---------
New Features
- Added support to update `display_name` attribute of `confluent_service_account` accounts
Checklist
---------
What
----
In previous versions of the Terraform provider updating the `display_name` attribute of `confluent_service_account` resources caused a resource replacement because the backend api did not support updates for display-names. 
Previous versions:
```hcl
-/+ resource "confluent_service_account" "app-manager" {
~ api_version  = "iam/v2" -> (known after apply)
~ display_name = "app-manager" -> "app-manager-updated" # forces replacement
~ id           = "sa-vxrm0z" -> (known after apply)
~ kind         = "ServiceAccount" -> (known after apply)
}
```
With this pr:
```hcl
~ resource "confluent_service_account" "app-manager" {
~ display_name = …
```
=> APIT-2981: Updated the service account resource to support changes to the display_name attribute, alongside the description.

internal/provider/resource_api_key.go
Release Notes
---------
NA
Checklist
---------
What
----
This PR does 2 things:
* adds time.Sleep() for Tableflow API Key just in case.
* updates sleeping time for SR and Flink API Keys from 2 minutes to 1 minute (FWIW it seems like 5-10 seconds should be sufficient anyway).
Note: it also uses `SleepIfNotTestMode(1*time.Minute, c.isAcceptanceTestMode)` instead of `time.Sleep(1 * time.Minute)` to make sure our acceptance tests are still quick.
Blast Radius
----
- Confluent Cloud customers who are creating new instances of `confluent_api_key` resource will be blocked.
References
----------
NA
Test & Review
-------------
* https://confluent.slack.com/archives/C08H9NWM0TG/p1742230082294999 (we verified SR & Flink API key creation, along with subsequent schema and statement creation, without …
=> Add time.Sleep() for Tableflow API Key.

internal/provider/resource_flink_statement.go
Release Notes
---------
Bug Fixes
- Update the error messages for `confluent_flink_statement` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_flink_statement).
Checklist
---------
What
----
Blast Radius
----
- Confluent Cloud customers who are using `confluent_flink_statement` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_flink_statement) will be blocked.
References
----------
* https://confluentinc.atlassian.net/browse/APIT-2991
Test & Review
-------------
* https://confluent.slack.com/archives/C02TG07V058/p1741982805772009
=> APIT-2991: Add descriptive error messages to resourceFlinkStatementDiff()

docs/data-sources/confluent_network.md, docs/resources/confluent_network.md
Release Notes
---------
New Features
- Release the `reserved_cidr` attribute and `zone_info` blocks are in [General Availabiliity lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy). It's available only for AWS networks with PEERING and TRANSITGATEWAY connection type.
Checklist
---------
NA
What
----
NA
Blast Radius
----
NA
References
----------
NA
Test & Review
-------------
NA
=> Remove LA label from confluent_network.md

examples/configurations/dedicated-vpc-peering-v2-aws-kafka-acls/terraform.tfvars
Release Notes
---------
NA
Checklist
---------
NA
What
----
This PR updates a typo in the dedicated-vpc-peering-v2-aws-kafka-acls example.
https://docs.confluent.io/cloud/current/networking/peering/aws-peering.html#requirements-and-considerations
> All AWS availability zones, except use1-az3 in the us-east-1 region, are supported.
Blast Radius
----
NA
References
----------
NA
Test & Review
-------------
=> Fix a typo in the dedicated-vpc-peering-v2-aws-kafka-acls

docs/resources/confluent_flink_artifact.md, internal/provider/resource_custom_connector_plugin.go, internal/provider/resource_flink_artifact.go, internal/provider/resource_flink_artifact_aws_test.go, internal/provider/resource_flink_artifact_azure_test.go, internal/provider/utils.go, internal/testdata/flink_artifact/create_artifact_azure.json, internal/testdata/flink_artifact/read_created_artifact_azure.json
Release Notes
---------
New Features
- Added Terraform support for Flink UDF artifact upload for Azure cloud.
Bug Fixes
Examples
Checklist
---------
What
----
The existing terraform supports uploading a Flink UDF artifact for AWS, this extends that to support Azure.
Blast Radius
----
Flink artifact UDF upload users
References
----------
https://confluentinc.atlassian.net/browse/CLI-3427?focusedCommentId=3696302
Test & Review
-------------
I also conducted the same test above and verified the Flink artifact was created for AWS which was the existing functionality (it was also visible in the UI). For Azure, it won't show up in the UI but that is expected as that work …
=> [CLI-3427] Terraform Support - Flink UDF on Azure

internal/provider/resource_kafka_cluster_config.go, internal/provider/resource_kafka_cluster_config_provider_block_test.go, internal/provider/resource_kafka_cluster_config_test.go, internal/testdata/kafka_config/read_updated_kafka_config.json
Release Notes
---------
Bug Fixes
- Resolved "error creating / updating Cluster Config: "ssl.enabled.protocols" cluster setting is read-only and cannot be updated" issue.
Checklist
---------
What
----
This PR resolves "error creating / updating Cluster Config: "ssl.enabled.protocols" cluster setting is read-only and cannot be updated" error that users could observe when trying to update / create Kafka Cluster Config using new "ssl.enabled.protocols" [attribute](https://docs.confluent.io/cloud/current/clusters/broker-config.html#change-cluster-settings-for-dedicated-clusters):
For example,
```
resource "confluent_kafka_cluster_config" "main" {
config = {
"ssl.enabled.protocols" = "TLSv1.2"
"log.retention.ms"      = "604800123"
}
}
```
Thanks to @bob-barrett for proactively suggesting a fix …
=> INC-1434: Resolve "error creating / updating Cluster Config: "ssl.enabled.protocols" cluster setting is read-only and cannot be updated" error

internal/provider/resource_identity_provider.go, internal/provider/resource_identity_provider_test.go, internal/testdata/identity_provider/read_updated_identity_provider.json
Release Notes
---------
New Features
- The `issuer` and `jwks_uri` attributes for the `confluent_identity_provider` resource can now be updated
Bug Fixes
Examples
Checklist
---------
What
----
The API was updated a while ago to make `issuer` and `jwks_uri` mutable, but the TF resource was not updated to reflect this change.
This PR removes the `force_new` setting from these attributes.
Blast Radius
----
The identity provider resource would be impacted.
References
----------
https://confluentinc.atlassian.net/browse/INC-1814
https://confluentinc.atlassian.net/browse/CLI-3545
Test & Review
-------------
* https://confluent.slack.com/archives/C08H9NWM0TG/p17455191557283 …
=> [INC-1814,CLI-3545] Allow updating `jwks_uri` and `issuer` in `confluent_identity_provider` resource

docs/resources/confluent_schema_registry_cluster_config.md, docs/resources/confluent_subject_config.md
Release Notes
---------
Bug Fixes
- Updated the docs.
Checklist
---------
NA
What
----
This PR updates TF docs to indicate how to configure configs at the global "context" level even though there're only 2 available APIs:
1. cluster-level API: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#config
2. subject-level API: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#put--config-(string-%20subject)
Blast Radius
----
None
References
----------
* https://confluentinc.atlassian.net/browse/CLI-3541
* https://confluentinc.atlassian.net/browse/DOCS-33540
Test & Review
-------------
* https://confluentinc.atlassian.net/browse/CLI-3541
* https://confluent.slack.com/archives/CM6PEBEGM/p1745536500407019?thread_ts=1745476395.681049&cid=CM6PEBEGM …
=> CLI-3541: Update TF docs to indicate how to configure configs at the global context level

docs/resources/confluent_schema_registry_cluster_mode.md, docs/resources/confluent_subject_mode.md, internal/provider/data_source_schema_registry_cluster_mode.go, internal/provider/data_source_subject_mode.go, internal/provider/resource_schema.go, internal/provider/resource_schema_registry_cluster_mode.go, internal/provider/resource_schema_registry_cluster_mode_provider_block_test.go, internal/provider/resource_schema_registry_cluster_mode_test.go, internal/provider/resource_subject_mode.go, internal/provider/resource_subject_mode_provider_block_test.go, internal/provider/resource_subject_mode_test.go
Release Notes
---------
Bug Fixes
- Added support for `force` attribute available in the SR API ([1](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#put--mode), [2](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#put--mode-(string-%20subject))) to the `confluent_schema_registry_cluster_mode` and `confluent_subject_mode` resources.
Checklist
---------
What
----
This PR fixes the following errors:
```
Error: error creating Subject Mode: 422 Cannot import since found existing subjects; error code: 42205: Cannot import since found existing subjects; error code: 42205
```
and
```
Error: error creating Schema Registry Cluster Mode: 422 Cannot import since found existing subjects; error code: 42205: Cannot import since found existing …
```
=> CLI-3546: Add new "force" attribute to confluent_schema_registry_cluster_mode, confluent_subject_mode resources

docs/resources/confluent_schema_exporter.md, internal/provider/resource_schema_exporter.go, internal/provider/resource_schema_exporter_provider_block_test.go, internal/provider/resource_schema_exporter_test.go, internal/provider/utils_wait.go, internal/testdata/schema_exporter/starting_status.json
Release Notes
---------
Bug Fixes
- Updated `confluent_schema_exporter` resource to resolve time out issues for create and update operations.
Checklist
---------
What
----
This PR updates the confluent_schema_exporter resource to treat the "STARTING" status as "RUNNING" to speed up the provisioning and update processes.
Blast Radius
----
- Confluent Cloud customers who are using `confluent_schema_exporter` resource will be blocked.
References
----------
NA
Test & Review
-------------
* https://confluent.slack.com/archives/C08H9NWM0TG/p1746559869336479
=> INC-2102: Resolve timeout errors for confluent_schema_exporter resource

internal/provider/resource_schema_exporter.go, internal/provider/utils_wait.go
Release Notes
---------
Bug Fixes
- Resolved "Error: error waiting for Schema Exporter "lsrc-abc123/exporter" to provision: couldn't find resource (21 retries).
Checklist
---------
What
----
Even though the code specified 4 hour timeout for schema exporter creation:
* https://github.com/confluentinc/terraform-provider-confluent/blob/v2.24.0/internal/provider/resource_schema_exporter.go#L120
* https://github.com/confluentinc/terraform-provider-confluent/blame/v2.24.0/internal/provider/utils_wait.go#L548
* https://github.com/confluentinc/terraform-provider-confluent/blob/v2.24.0/internal/provider/resource_schema_exporter.go#L48
we could still observe this issue where TF was timing out after just 10 minutes consistently when creating a schema exporter instance:
``` …
```
=> INC-2201: Resolve "Error: error waiting for Schema Exporter "lsrc-abc123/exporter" to provision: couldn't find resource (21 retries)

internal/provider/resource_api_key.go, internal/provider/resource_api_key_test.go, internal/provider/resource_role_binding.go, internal/provider/resource_role_binding_test.go
Release Notes
---------
Bug Fixes
- Resolved forced replacement when updating the value of the disable_wait_for_ready attribute
Checklist
---------
What
----
This PR resolves forced replacement when updating the value of the `disable_wait_for_ready` attribute for `confluent_api_key` and `confluent_role_binding` resources.
**Why did we choose to implement DiffSuppressFunc instead of supporting in-place updates?**
Initially, we implemented in-place updates. However, we realized this approach can be confusing for users—Terraform would detect a drift, but the update would be a no-op, leading to unnecessary apply actions with no actual impact, other than updating the value of disable_wait_for_ready in the Terraform state. This creates a poor user experience by prompting users to apply a …
=> INC-2161: Resolve forced replacement when updating the value of the disable_wait_for_ready attribute

internal/provider/resource_api_key.go, internal/provider/resource_api_key_test.go, internal/provider/resource_role_binding.go, internal/provider/resource_role_binding_test.go
Release Notes
---------
NA
Checklist
---------
What
----
This PR reverts #685. We identified a bug where all new role bindings had disable_wait_for_ready = false, regardless of the value of this attribute in the TF configuration.
Blast Radius
----
NA, as this is a full revert of #685 that wasn't released yet.
References
----------
* https://confluentinc.atlassian.net/browse/APIE-16
Test & Review
-------------
NA, as this is a full revert of #685 that wasn't released yet.
=> APIE-16: Revert #685

internal/provider/resource_cluster_link.go
Release Notes
---------
Bug Fixes
- Update the `confluent_cluster_link` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_cluster_link) to allow specifying a custom value for the "topic.config.sync.include" configuration parameter.
Checklist
---------
- [] I have included appropriate Terraform acceptance or unit tests for any new resource, data source, or functionality.
What
----
This PR updates the confluent_cluster_link resource to allow specifying a custom value for the "topic.config.sync.include" configuration parameter.
Blast Radius
----
- Confluent Cloud customers who are using `confluent_cluster_link` resource/data-source will be blocked.
References
----------
* https://docs.confluent.io/platform/current/multi-dc-deployments/cl …
=> APIE-428: Update the confluent_cluster_link resource to allow specifying a custom value for the "topic.config.sync.include" configuration parameter.

.semaphore/goreleaser.yml
This PR updates `goreleaser.yml` to fix:
```
compile: version "go1.23.10" does not match go tool version "go1.22.7"
```
We realized `goreleaser.yml` was missing `sem-version go 1.22.7` in the `goreleaser-darwin-fips` job.
=> #minor: prepare for v2.33.0 minor release: Set "sem-version go 1.22.7" in goreleaser-darwin-fips

.semaphore/goreleaser.yml
* https://confluent.slack.com/archives/C09EP1SS3/p1751475467861449?thread_ts=1751411143.543079&cid=C09EP1SS3
=> #minor: prepare for v2.33.0 minor release: Fix CI failure during "goreleaser-darwin-fips" step

.semaphore/goreleaser.yml
* https://confluent.slack.com/archives/C09EP1SS3/p1751482229512319?thread_ts=1751411143.543079&cid=C09EP1SS3
=> #minor: prepare for v2.33.0 minor release: Update the commands order in the goreleaser-darwin-fips task

internal/provider/factory_utils.go, internal/provider/utils.go
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
Add descriptive error message for status code 429
Blast Radius
----
None. Only modifying error message for status code 429
References
----------
https://confluentinc.atlassian.net/browse/APIE-425
Test & Review
-------------
For 429 status: 
For other status: 
For 150 data source reads of environment:
1. Current behaviour
2. New behaviour
For 100 reads in both scenarios:
=> Add descriptive error for 429

.github/pull_request_template.md, Makefile
Release Notes
---------
NA
Checklist
---------
NA
What
----
This PR addresses #707 and #708, namely, it 
* updates PR template (#707)
* removes `build-all` target that is no longer used anywhere in the codebase (#708)
Blast Radius
----
NA
References
----------
* https://confluentinc.atlassian.net/browse/APIE-481
Test & Review
-------------
We verified that the build-all target is not used anywhere by searching for exact matches in this project.
=> APIE-481: Update PR Template & Remove Unused Make Target

go.mod, go.sum, internal/provider/oauth.go, internal/provider/provider.go, internal/provider/utils.go
Release Notes
---------
New Features
Bug Fixes
- For OAuth feature, replace the raw HTTP client with STS specific HTTP client from Confluent Cloud SDK to have standard HTTP request header.
Examples
Checklist
---------
What
----
Previously, when sending POST request to STS service to exchange for a STS token, a raw HTTP client was used, which was less ideal as we should have a standard HTTP request header.
```    req, err := http.NewRequest(http.MethodPost, stsEndpoint, strings.NewReader(data.Encode()))
if err != nil {
return nil, err
}
req.Header.Set("content-type", "application/x-www-form-urlencoded")
req.Header.Set("accept", "application/json")
``` …
=> [CLI-3511] Replace the raw STS token exchange HTTP request with public SDK

examples/configurations/cluster-link-using-oauth/advanced-bidirectional-cluster-link-using-oauth/main.tf, examples/configurations/cluster-link-using-oauth/advanced-bidirectional-cluster-link-using-oauth/terraform.tfvars, examples/configurations/cluster-link-using-oauth/advanced-bidirectional-cluster-link-using-oauth/variables.tf, examples/configurations/cluster-link-using-oauth/destination-initiated-cluster-link-using-oauth/main.tf, examples/configurations/cluster-link-using-oauth/destination-initiated-cluster-link-using-oauth/terraform.tfvars, examples/configurations/cluster-link-using-oauth/destination-initiated-cluster-link-using-oauth/variables.tf, examples/configurations/cluster-link-using-oauth/regular-bidirectional-cluster-link-using-oauth/main.tf, examples/configurations/cluster-link-using-oauth/regular-bidirectional-cluster-link-using-oauth/terraform.tfvars, examples/configurations/cluster-link-using-oauth/regular-bidirectional-cluster-link-using-oauth/variables.tf, go.mod, go.sum, internal/provider/resource_cluster_link.go, internal/provider/resource_kafka_mirror_topic.go
Release Notes
---------
New Features
- Added OAuth support for `confluent_cluster_link` resource and data-source.
Bug Fixes
Examples
- Added 3 OAuth examples for `confluent_cluster_link` resource, `destination-initiated` type, `regular-bidirectional` type, and the `advanced-bidirectional` type.
Checklist
---------
What
----
This PR involves a code refactoring to update the SASL configuration to support `OAUTHBEARER` as the SASL mechanism.
3 examples `destination-initiated` type, `regular-bidirectional` type, and the `advanced-bidirectional` type have been validated and added to example folder to help users bringing up the OAuth feature.
Previous implementation always assumes the API key/secret exists, and for users with OAuth, this …
=> [CLI-3586] OAuth support for Kafka cluster link

Makefile
Release Notes
---------
New Features
Bug Fixes
Examples
Checklist
---------
What
----
`findstring` is trying to find the literal strings `\#major` `\#minor` and `\#patch` instead of treating the `\` as an escape character. This is causing `BUMP` to always end up as `DEFAULT_BUMP`.
Blast Radius
----
References
----------
Test & Review
-------------
Tested in an Ubuntu docker image using the following debugging make target:
```
.PHONY: print-versions
print-versions:
@echo "VERSION: $(VERSION)"
@echo "CLEAN_VERSION: $(CLEAN_VERSION)"
@echo "GIT_MESSAGES: $(GIT_MESSAGES)"
@echo "BUMP: $(BUMP)"
@echo …
```
=> [APIE-553] Fix auto bump for tags

internal/provider/data_source_ksql_cluster_live_test.go, internal/provider/resource_ksql_cluster_live_test.go
Release Notes
---------
N/A, as this PR resolves failing tests.
Checklist
---------
N/A, as we only updated test files:
What
----
This PR resolves failing live tests:
* FAIL: TestAccKsqlClusterDataSourceLive
* FAIL: TestAccKsqlClusterLive
by updating the csu number to a higher value to be the minimum supported amount:
> You select the number of CSUs for your cluster at provisioning time. You can configure CSUs as follows:
> 4 CSUs is the minimum.
> 28 CSUs is the maximum.
> Cluster sizes can be 4, 8, 12, 16, 20, 24, or 28 CSUs.
> source: https://docs.confluent.io/cloud/current/ksqldb/overview.html
```
error creating ksqlDB Cluster "": 400 Bad Request: Cluster configuration is invalid:01:09
csu_min: Cluster creation failed. A minimum of 4 CSUs is required for new ksqlDB clusters.
```
Blast …
=> APIE-585: Resolve failing live tests: TestAccKsqlClusterDataSourceLive, TestAccKsqlClusterLive

internal/provider/factory_utils.go
Release Notes
---------
N/A, as this PR does not introduce any user-facing changes. Instead, it improves TF logging which will be useful for debugging.
Checklist
---------
What
----
This PR adds automatic request ID logging to HTTP transport layer for improved debugging and request tracing. This enhancement captures the server-generated x-request-id header from API responses and logs it alongside request details, enabling easier correlation between Terraform operations and server-side logs.
Blast Radius
----
All users will be blocked if the HTTP transport wrapper fails, as this affects the primary HTTP client used for all API requests.
**Why it's safe**: The logging logic is minimal (just header extraction and debug logging) and follows standard Go HTTP patterns. The wrapper simply calls …
=> APIE-578: Add request ID logging to HTTP transport for improved debugging

docs/resources/confluent_tag_binding.md, internal/provider/data_source_tag_binding.go, internal/provider/resource_tag_binding.go, internal/provider/resource_tag_binding_test.go
Release Notes
---------
New Features
- Add `disable_wait_for_ready` attribute to disable readiness checks for `confluent_tag_binding` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_tag_binding).
Checklist
---------
What
----
This PR adds `disable_wait_for_ready` attribute to disable readiness checks for `confluent_tag_binding` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_tag_binding). The primary use case for using this flag is when you need to quickly provision a lot of tag bindings, if all the tags have already been provisioned before.
The implementation and the attribute naming were copied from the following PRs:
* …
=> APIE-482: Add disable_wait_for_ready attribute to disable readiness checks for confluent_tag_binding resource 

.semaphore/goreleaser.yml, internal/provider/resource_tf_importer.go
Release Notes
---------
Bug Fixes
- Fixed confluent_tf_importer's timeout issues when importing huge number of resources (for example, 2'000+ Kafka topics).
Checklist
---------
What
----
Before this PR, users could experience timeout issues when trying to import a huge number of resources (2'000+ Kafka topics):
```
[20m23s elapsed]
confluent_tf_importer.example: Still creating... [20m33s elapsed]
confluent_tf_importer.example: Still creating... [20m43s elapsed]
confluent_tf_importer.example: Still creating... [20m53s elapsed]
╷
│ Error: Failed to get state for confluent_kafka_topic instance lkc-526pjn/topic_586: [{0 error reading Kafka Topic: Get "[https://pkc-921jm.us-east-2.aws.confluent.cloud:443/kafka/v3/clusters/lkc-526pjn/topics/topic_586](https://pkc-921jm.us-east-2.aws.confluent.cl …
```
=> APIE-593: Fix confluent_tf_importer's timeout issues when importing huge number of resources

internal/provider/resource_kafka_topic.go, internal/provider/resource_kafka_topic_test.go
Release Notes
---------
Bug Fixes
- Updated the `confluent_kafka_topic` resource to support in-place update for the rest_endpoint attribute.
Checklist
---------
What
----
This PR adds support for in-place updates of the rest_endpoint attribute in the confluent_kafka_topic resource, addressing a bug where changes to this attribute would force resource recreation.
- Removed the ForceNew: true constraint from the rest_endpoint attribute schema
- Updated the update function to allow changes to rest_endpoint alongside other updatable parameters
- Enhanced test setup to use two separate WireMock containers to properly test the endpoint transition
Blast Radius
----
- Confluent Cloud customers who are using `confluent_kafka_cluster` resource may experience TF drift.
References
----------
* …
=> INC-5291: Support in-place update for the rest_endpoint attribute of the confluent_kafka_topic resource

internal/provider/oauth.go, internal/provider/resource_schema_exporter.go
Release Notes
---------
New Features
- Added error descriptions when token exchange request fails using OAuth authentication.
Bug Fixes
Examples
Checklist
---------
What
----
This PR is an enhancement on top of the existing OAuth authentication support, it includes more descriptive errors for when external/STS token exchange request fails.
The benefit is that users will have more context into why the Terraform fails plan/apply with better correction items, such as:
- Invalid client id/secret
- Invalid identity pool
- Incorrect scope
- Incorrect RBAC role for the identity pool
- Incorrect token request URL
- and so on
Also, this PR introduces a minor refactor on the …
=> [APIE-579] Show more descriptive errors when OAuth token exchange request fails

docs/resources/confluent_catalog_entity_attributes.md, internal/provider/resource_catalog_entity_attributes.go, internal/provider/resource_catalog_entity_attributes_test.go
Release Notes
---------
New Features
- Added import functionality for the `confluent_catalog_entity_attributes ` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_catalog_entity_attributes).
Checklist
---------
What
----
This PR (hot-fix) resolves a feature gap where `terraform import` was not supported for the `confluent_catalog_entity_attributes ` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_catalog_entity_attributes). This PR is a follow up item to the https://github.com/confluentinc/terraform-provider-confluent/issues/822.
The implementation strategy: 
1. Refactored read and import methods for code reuse
We refactored both the read and import methods to follow the same …
=> INC-5632: Add import functionality to confluent_catalog_entity_attributes resource.
